import { StyleSheet } from "react-native";
import {
  black,
  grey100,
  grey200,
  grey40,
  grey500,
  orange50,
  orange500,
  white,
} from "../../constants/colors";

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: white,
    paddingTop: 40,
    paddingHorizontal: 16,
  },
  topContainer: {
    paddingTop: 25.5,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: grey40,
  },
  activityBar: {
    width: 60,
    height: 30,
    borderRadius: 75,
    backgroundColor: grey40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8.25,
  },
  activeActivityBar: {
    width: 60,
    height: 30,
    borderRadius: 75,
    backgroundColor: orange500,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8.25,
  },
  activityBarDot: {
    width: 18,
    height: 18,
    backgroundColor: white,
    borderRadius: 100,
  },
  activityBarText: {
    fontSize: 7.5,
    lineHeight: 10,
    fontFamily: 'satoshi-bold',
    color: grey500,
    fontWeight: '700',
  },
  activeActivityBarText: {
    fontSize: 7.5,
    lineHeight: 10,
    fontFamily: 'satoshi-bold',
    color: white,
    fontWeight: '700',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  searchBar: {
    flexDirection: "row",
    marginTop: 26.5,
    backgroundColor: grey100,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
    gap: 8,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: "satoshi",
  },
  filter: {
    transform: [{ rotate: "90deg" }],
  },
  tabTitle: {
    fontWeight: "700",
    fontSize: 20,
    lineHeight: 27,
    color: black,
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 20,
  },
  modalContainer: {
    backgroundColor: white,
    width: "100%",
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderRadius: 10,
  },
  closeContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  closeIcon: {
    width: 50,
    height: 5,
    borderRadius: 100,
    backgroundColor: "#D9D9D9",
  },
  detailText: {
    color: grey500,
    fontSize: 10,
    fontFamily: 'satoshi',
    fontWeight: "400",
  },
  rightText: {
    textAlign: "right",
    color: grey500,
    fontSize: 10,
    fontWeight: "400",
    width: 166,
  },
  detailContainer: {
    padding: 10,
    backgroundColor: orange50,
    borderRadius: 8,
    gap: 4,
  },
  modalPrice: {
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 19,
    color: grey500,
  },
  idText: {
    color: grey500,
    fontSize: 14,
    lineHeight: 19,
  },
  timeAway: {
    color: grey500,
    fontSize: 12,
    lineHeight: 16,
    marginTop: 12,
  },
  modalTop: {
    marginBottom: 40,
    gap: 12,
    borderBottomColor: '#F4F4F6',
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontWeight: "700",
    fontSize: 18,
    lineHeight: 24.3,
    color: grey500,
  },
  btnsContainer: {
    flexDirection: "row",
    gap: 16,
    paddingTop: 20,
    marginBottom: 32,
  },
  btnContainer: {
    flex: 0.5,
  },
  filterText: {
    lineHeight: 22,
    fontSize: 14,
    color: grey200,
  },
  filterTextContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
  },
  activeFilterTextContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: orange500,
  },
  filterBtnContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});
